### ISSUE TITLE
SP Shooter: Error handling response: TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by kofrimpong** [pnp/sp-editor#53]
Browser
Microsoft Edge
Version 114.0.1823.67 (Official build) (64-bit)

SP Editor
Version 6.6.1

SP Shooter does not open. It throws "Error handling response: TypeError: Cannot read properties of undefined (reading 'id')" when you try to open it.

**Comment by tavikukko** [comment]
Hi @kofrimpong 
And that you for reporting. I tested with Chrome and Edge and I don't get this error.
What is the SharePoint page you are when you open the Extension? Where do you see the error message.

Thanks!

**Comment by kofrimpong** [comment]
@tavikukko When you dock the developer tools into separate window.

**Comment by tavikukko** [comment]
Got it, I will have look, thanks!

**Comment by tavikukko** [comment]
Found a fix, will try to release as soon as possible.
Thanks @kofrimpong for you rapid response, for me it took some time because on vacation.

Cheers!

**Comment by tavikukko** [comment]
Fixed version uploaded to Edge store, waiting for the store review, might take some time. Thanks again!
