### ISSUE TITLE
SP-Editor Edge edition keeps crashing 

### ISSUE THREAD

**Issue by zumiek** [pnp/sp-editor#56]
Hi,
For some reason the extension crashes when I try to open the PnPJS console.
Repairing or re-installing doesn't seem to help.
Any tips on how to troubleshoot it or do I need to re-install Edge (not that happy with that idea with all the profiles etc...)
![image](https://github.com/pnp/sp-editor/assets/1893244/6ea1cdd8-949b-4ed0-8ccc-4e481ddb9fb0)

**Comment by tavikukko** [comment]
Hi @zumiek 
and thanks you for reporting. Can you share the version number of the Edge browser, thanks!

**Comment by zumiek** [comment]
![image](https://github.com/pnp/sp-editor/assets/1893244/befa9e93-816a-43d8-9599-884914d5010e)

**Comment by tavikukko** [comment]
I am using mac and cannot get it to crash, hard to say if it is the extension or the browser. I can see you have Edge for business, could there be some restrictions from the company?

**Comment by zumiek** [comment]
Maybe, the Chrome version works fine though...
I'll try it on another client from another company.

**Comment by zumiek** [comment]
It worked fine on another client with the same Edge version, so my bad, It's probably something with my comp. will try and re-install Edge and see if that helps, I didn't see any specific Extension policy blocking anything, on the other hand It might be time for a clean install of my client...

**Comment by tavikukko** [comment]
Thanks @zumiek for the information, will close this then. 
If you find out anything related to this issue,  let me know, thanks!
