### ISSUE TITLE
Quick link to "All People"

### ISSUE THREAD

**Issue by jackpoz** [pnp/sp-editor#57]
I would like to have a Quick link that points to the "All People" page as /_layouts/people.aspx?MembershipGroupId=0 .

Quite often I end up having to remove some deleted/expired Entra ID users from a SPO site so that they can be reinvited.

**Comment by tavikukko** [comment]
Hi @jackpoz !
Thanks for the idea, will add it, and sorry for the late reply!
I am just finishing the Search feature, will add link to All People with the same release!

Cheers!
