### ISSUE TITLE
SP Shooter ignores custom headers

### ISSUE THREAD

**Issue by kofrimpong** [pnp/sp-editor#61]
SP Shooter ignores custom headers. I have the following in the headers tab
```json
{
  "accept": "application/json",
  "content-type": "application/json"
}
```
but the request sent has

Accept: application/json, application/json; odata=verbose
Content-Type: application/json, application/json;charset=utf-8

**Comment by tavikukko** [comment]
Thanks @kofrimpong reporting!
I will take a look!

**Comment by tavikukko** [comment]
Hi @kofrimpong! Just releised to new version, could you test it out, thanks!

**Comment by tavikukko** [comment]
fixed, please create new if still issue, thanks @kofrimpong
