### ISSUE TITLE
SP OnPrem - Search is not working

### ISSUE THREAD

**Issue by diabhoil** [pnp/sp-editor#63]
The extension tries to request the context via _api/contextinfo but the headers send are wrong. It receives XML instead of JSON and fails with an error:

![grafik](https://github.com/user-attachments/assets/65591427-2ff5-4ac9-89cf-f3bbd57a5812)

PS: the explanaiting in the README is wrong. There is no "watch" task and the "start" or "cracostart" task do not create the required manifest file for Edge to load the extension.

**Comment by tavikukko** [comment]
Thanks @diabhoil !
Could you please paste the headers sent to _api/contextinfo 

And yes, need to update the Readme with updated instructions.

**Comment by tavikukko** [comment]
Ok, this seems to be issue in PnPJS, and its the backbone of SP Editor. Could you test, what else is failing in OnPrem? Thanks!

**Comment by tavikukko** [comment]
Wow, thank you @diabhoil !
I think i can get forward with this information!

**Comment by tavikukko** [comment]
Fixed in the latest version 7.2.0
Could you test when possible, thanks @diabhoil !
