### ISSUE TITLE
File Editor not working and warning displayed

### ISSUE THREAD

**Issue by mix1981** [pnp/sp-editor#66]
Am I the only one that SP Editor stopped working? Chrome is displaying warning, that this extension could be dangerous, but the worse thing is that File Explorer is not working at all - it's still (Working on it..)
![warning](https://github.com/user-attachments/assets/1c84495f-cc78-4f78-98ff-f849a79c5fbb)

**Comment by tavikukko** [comment]
Hi @mix1981 !
SP Editor got major update and still some features are not implemented, and you see the text Working on it... (an inside joke for SharePointers). 

Could you take screen capture of the warning text where is mentioned that this extension might be dangerous? If its the image you have attached, its warning from the extension, just to let you know that this tool is powerfull, and you should be using it carefully.

**Comment by mix1981** [comment]
Ohh, ok, now is everything clear. I was thinging that Working on it... means that some backgroud task failed and that's why no result is displayed :) 
And as for warning - no, just this "Star Wars style" warning appears. So sorry for false alert :)

**Comment by tavikukko** [comment]
FYI: File Editor is implemented now @mix1981
