### ISSUE TITLE
Add copy option ?

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/sp-editor#70]
I have no idea if this blocked by the browser or not, so here goes:

Would it be possible to select and copy the values shown in the Search tab. In this case I would like to copy the guid, as my memory isn't what it used to be ;-)

![image](https://github.com/user-attachments/assets/93406540-d717-47db-9ba4-031d645c0b07)

**Comment by tavikukko** [comment]
Added buttons to copy property name and the value, released to Chrome Store v7.0.4 now available. Please test @kasperbolarsen
