### ISSUE TITLE
Plugin not working at all 

### ISSUE THREAD

**Issue by pharaomar** [pnp/sp-editor#74]
Hey, when I click on the plug in it turns blank as soon as I am on a Sharepoint Page.

<img width="794" alt="image" src="https://github.com/user-attachments/assets/ff9f8e89-1afc-4ffb-aa17-37bdd293d747">

I attached an image!
Thanks,
Omar

**Comment by pharaomar** [comment]
I am using version 7.1.0 of the editor
and chrome in version 128.0.6613.138

**Comment by tavikukko** [comment]
Also, are you using SharePoint Online/Onprem?

**Comment by pharaomar** [comment]
Hey, I am using Sharepoint online, and this is the error that I see in the console:

![image](https://github.com/user-attachments/assets/29124e5c-519f-4d60-957e-c6f2269870ac)


Thanks for the quick reply! :)

**Comment by tavikukko** [comment]
Hmm, hard to say... whats the environmemt, online/onprem?

**Comment by tavikukko** [comment]
And whats that page you at?

**Comment by tavikukko** [comment]
Are you signed in as a guest user etc? I need more information to be aboe to repro this, thanks.

**Comment by tavikukko** [comment]
Released new version with a fix, hope it works. The version is 7.1.2, should ve soon available. Comment here is it works ir not. If not, could you please check again the extension console for errors. Cheers!

**Comment by pharaomar** [comment]
Hey @tavikukko, works again! Thank you very much :)
