### ISSUE TITLE
Display raw response

### ISSUE THREAD

**Issue by kofrimpong** [pnp/sp-editor#76]
Is there a reason responses are formatted irrespective of the accept-header? For example, "accept": "application/json; odata=verbose" and "accept": "application/json; odata=minimalmetada" all show the same formatted response. Will it be possible to display the raw response.  Example verbose will have top level as d;{}

Thanks

**Comment by tavikukko** [comment]
Hi @kofrimpong 
Are you seeing this in SP Shooter, when setting the headers?

**Comment by kofrimpong** [comment]
Yes

**Comment by kofrimpong** [comment]
To clarify, in the response window of SP Shooter

**Comment by tavikukko** [comment]
thanks @kofrimpong 
Switching SPShooter parser from PnPJS DefaultParser  to PnPJS JSONparser seems to show the raw. Will change to that.
This will be part of the next release, hopefully soon!

**Comment by tavikukko** [comment]
![image](https://github.com/user-attachments/assets/b5712bc8-6af4-4187-95ed-9264812f8d06)

**Comment by kofrimpong** [comment]
With verbose header,

This is the response in browser
<img width="516" alt="image" src="https://github.com/user-attachments/assets/588f918b-894a-4c72-8d3b-431455154784">

This is the response in SP Shooter
![spshooter](https://github.com/user-attachments/assets/9ccae4b5-5adb-4e0e-bc54-6eb757e52ccf)

**Comment by tavikukko** [comment]
Ok, seems like json parser also cuts something. Lets see what can we do.

**Comment by tavikukko** [comment]
Well looks like its working with JSON parser after all, when I used also the lists endpoint. I think we good with this.
![image](https://github.com/user-attachments/assets/dbaffcad-94df-4064-a9b2-7f6225162bee)

**Comment by kofrimpong** [comment]
Can you share what you have under you Headers tab?

**Comment by tavikukko** [comment]
![image](https://github.com/user-attachments/assets/aac7592c-9a74-4325-ae30-9a932c35b099)
This is working because I'm debuging and fixed it locally.

**Comment by kofrimpong** [comment]
Okay

**Comment by tavikukko** [comment]
Fixed in the latest version 7.2.0
Could you test when possible, thanks @kofrimpong !
